Removed second value from "response"
CycloneDX/bom-examples pull request #35
Opened 2022-12-12 16:15 UTC by Walter-Haydock

As per conversation with @stevespringett - the response field should be exactly one item.

2023-02-22 09:33 UTC, jkowalleck commented on VEX/vex.json
> +        "response": "will_not_fix",
:x: per aplied JSON schema `response` is to be a list of known values. a LIST.
see also https://cyclonedx.org/docs/1.4/json/#vulnerabilities_items_analysis_response

2023-02-22 09:34 UTC, jkowalleck requested changes
Requested change would render the example to be an invalid document.

2023-02-26 17:57 UTC, Walter-Haydock commented
Ok - thanks. I see that it is supposed to be a list now and must have missed it at first. I still remain confused by the example, though. How would a valid response be both "will_not_fix" and "update"? I could see "workaround_available" and "update" but the example as stands implies that the vendor will not fix the issue but also that they will.

Any clarification here would be helpful.

2023-02-26 19:11 UTC, stevespringett commented
Common use case where a vendor states that an old EOL/EOS product is affected and that the customer should upgrade to a supported version.

2023-02-26 19:18 UTC, closed without merging